### ISSUE TITLE
Defconfig for Redmi Note 9 Pro (joyeuse)

### ISSUE THREAD

**Issue by 1DeMaCr** [ctwoon/caf-4.14#1]
Hello! Can you creat defconfig for Europe version of Redmi Note 9 Pro (joyeuse)?
Kernel with atoll-perf_defconfig can not start. Or is it need more changes?

**Comment by ctwoon** [comment]
Hello. I'm sorry but I don't own joyeuse. I own only global curtana (as I live in Russia) and I have no idea why your device wouldn't start as you didn't sent log here. Please reply with dmesg.

**Comment by 1DeMaCr** [comment]
I am from Russia else :) Can I write russian?
